# Generated by Django 3.2.4 on 2021-11-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20211016_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=1000)),
                ('post_content', models.CharField(max_length=5000)),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
