# Generated by Django 4.0.2 on 2022-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mentalH',
            field=models.CharField(default='suicide', max_length=100),
        ),
    ]
