# Generated by Django 3.2.4 on 2022-03-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_mentalh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reason',
            new_name='post_username',
        ),
    ]
