# Generated by Django 3.2.4 on 2021-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.CharField(max_length=1000),
        ),
    ]
