# Generated by Django 3.2.8 on 2021-10-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211016_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_bal',
            field=models.IntegerField(default=0),
        ),
    ]
