# Generated by Django 3.2.4 on 2021-11-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_bank_account_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='key',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
