# Generated by Django 3.2.4 on 2021-11-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_signup_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='key',
        ),
        migrations.AddField(
            model_name='editprofile',
            name='key',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
