# Generated by Django 4.0.2 on 2022-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211111_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofile',
            name='count_mentalH',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='editprofile',
            name='key',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
