# Generated by Django 3.2.4 on 2022-03-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_editprofile_count_mentalh_alter_editprofile_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofile',
            name='approval',
            field=models.IntegerField(default=1, max_length=20),
        ),
    ]
