# Generated by Django 3.2.4 on 2022-03-18 18:13

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_editprofile_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_username', models.CharField(max_length=1000)),
                ('doctype', models.CharField(max_length=1000)),
                ('doc_bio', models.CharField(max_length=2000)),
                ('doc_image', models.ImageField(blank=True, null=True, upload_to=home.models.filepath)),
            ],
        ),
    ]
