# Generated by Django 4.0.2 on 2022-03-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_exp',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_qualification',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_tpe',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
