# Generated by Django 4.0.2 on 2022-03-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_doctor_doc_exp_doctor_doc_qualification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctype',
            new_name='doc_type',
        ),
    ]
