# Generated by Django 4.0.2 on 2022-03-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_doctype_doctor_doc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doc_type',
        ),
    ]
