# Generated by Django 4.0.2 on 2022-03-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_doctor_doc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_tpe',
            new_name='doc_type',
        ),
    ]
