# Generated by Django 3.2.4 on 2022-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_doc_tpe_doctor_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofile',
            name='doc_assigned',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='editprofile',
            name='approval',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
