# Generated by Django 3.2.4 on 2022-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_username', models.CharField(max_length=1000)),
                ('required_sessions', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
