# Generated by Django 3.2.4 on 2022-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='doctor_username',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
