# Generated by Django 3.2.4 on 2022-03-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_session_doctor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='completed_sessions',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
