# Generated by Django 3.2.4 on 2022-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_session_completed_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_username', models.CharField(max_length=1000)),
                ('required_reports', models.IntegerField(max_length=1000)),
                ('completed_reports', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
