# Generated by Django 4.0.2 on 2022-03-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportDoc',
        ),
    ]
